{
 "title": "Druid metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Segments and datasources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"display:flex; justify-content:center; align-items:center; height: 100%; text-align:center;\">\n    <img src=\"https://druid.apache.org/img/druid_nav.png\" height=\"60\" width=\"160\">\n</p>"
   }
  },
  {
   "title": "Unload segments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_expo_segment_loadQueue_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Segments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(druid_expo_segment_count)", "legendFormat": "{{datasource}}" }
   ]
  },
  {
   "title": "Datasource count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(druid_expo_segment_assigned_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(druid_expo_segment_size)", "legendFormat": "{{datasource}}" }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(service) (druid_expo_sys_cpu{cpu_time=~\"sys|user\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "druid_expo_sys_swap_free", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Free memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(service) (druid_expo_sys_mem_free)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "JVM Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(service) (druid_expo_jvm_mem_used)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM Memory pool",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(service) (druid_expo_jvm_pool_used)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Disk write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "druid_expo_sys_disk_write_count",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "druid_expo_sys_disk_read_size", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Disk queue",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service) (druid_expo_sys_disk_queue)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Disk transfer time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(service) (druid_expo_sys_disk_transferTime)",
     "legendFormat": "{{service}} - avg"
    },
    {
     "expr": "max by(service) (druid_expo_sys_disk_transferTime)",
     "legendFormat": "{{service}} - max"
    },
    {
     "expr": "min by(service) (druid_expo_sys_disk_transferTime)",
     "legendFormat": "{{service}} - min"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(service) (druid_expo_sys_fs_used)",
     "legendFormat": "{{service}}  {{instance}}"
    }
   ]
  },
  { "title": "Queries and ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Query time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "druid_expo_sqlQuery_time", "legendFormat": "Time {{id}}" },
    { "expr": "druid_expo_query_time", "legendFormat": "Time {{id}}" }
   ]
  },
  {
   "title": "Query Bytes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(druid_expo_query_bytes)", "legendFormat": "total - query client" },
    { "expr": "sum(druid_expo_sqlQuery_bytes)", "legendFormat": "total - query executed" }
   ]
  },
  {
   "title": "Query count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service) (druid_expo_query_failed_count)",
     "legendFormat": "{{service}} - failed"
    },
    {
     "expr": "sum by(service) (druid_expo_query_success_count)",
     "legendFormat": "{{service}} - success"
    },
    {
     "expr": "sum by(service) (druid_expo_query_count)",
     "legendFormat": "{{service}} - count"
    },
    {
     "expr": "sum by(service) (druid_expo_task_interrupt_count)",
     "legendFormat": "{{service}} - interrupt"
    }
   ]
  },
  {
   "title": "Query Wait time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "druid_expo_query_wait_time", "legendFormat": "{{datasource}}" }
   ]
  },
  {
   "title": "Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(host, instance) (druid_expo_ingest_events_processed)",
     "legendFormat": "{{host}} - {{instance}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "AVG Idle http threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "avg by(service) (druid_expo_jetty_threadPool_idle)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Opened connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(service) (druid_expo_jetty_numOpenConnections)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}